apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-frontend-deployment
  labels:
    app: emp-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp-frontend
  template:
    metadata:
      labels:
        app: emp-frontend
    spec:
      containers:
        - name: emp-frontend
          image: shreyaskale15/emp_frontend_final:64
          ports:
            - containerPort: 4200

